apiVersion: v1
kind: Service
metadata:
  labels:
    cloud-pipeline/cp-sensitive-proxy: "true"
  name: cp-sensitive-proxy
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: ${CP_TP_INTERNAL_PORT}
    targetPort: ${CP_TP_INTERNAL_PORT}
    name: cp-sensitive-proxy-port
  selector:
    cloud-pipeline/cp-sensitive-proxy: "true"
